import React, { useState, useRef, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { useNavigate } from 'react-router-dom'
import { Canvas, useFrame } from '@react-three/fiber'
import { MapControls, useTexture } from '@react-three/drei'
import * as THREE from 'three'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { ArrowLeft, ArrowRight, Sun, Layers, SlidersHorizontal, MousePointer2 } from 'lucide-react'

// WebGL Leaf Shader Component
function LeafRelight({ lightAzimuth, lightElevation, contrast }: { lightAzimuth: number, lightElevation: number, contrast: number }) {
  // In a real app we'd load the normal map and albedo generated by the backend.
  // We'll use the synthetic raking images to create a fake normal map effect or just use a standard standard material
  const albedo = useTexture('/assets/leaf_RING.jpg')
  const normalMap = useTexture('/assets/leaf_N.jpg') // Fake normal map for demo purposes
  
  // Calculate light direction vector
  const theta = (lightAzimuth * Math.PI) / 180
  const phi = (lightElevation * Math.PI) / 180
  const lx = Math.cos(phi) * Math.cos(theta)
  const ly = Math.cos(phi) * Math.sin(theta)
  const lz = Math.sin(phi)
  
  const lightDir = new THREE.Vector3(lx, ly, lz)

  return (
    <mesh>
      <planeGeometry args={[10, 2.5]} />
      <meshStandardMaterial 
        map={albedo}
        normalMap={normalMap}
        normalScale={new THREE.Vector2(contrast, contrast)}
        roughness={0.8}
        metalness={0.1}
      />
      <directionalLight position={[lightDir.x * 10, lightDir.y * 10, lightDir.z * 10]} intensity={2.0} />
      <ambientLight intensity={0.2} />
    </mesh>
  )
}

export default function Reveal() {
  const navigate = useNavigate()
  
  const [azimuth, setAzimuth] = useState(45)
  const [elevation, setElevation] = useState(15)
  const [contrast, setContrast] = useState(1.5)
  const [showCurtain, setShowCurtain] = useState(false)
  const [curtainPos, setCurtainPos] = useState(50) // percentage
  
  // Calculate legibility score based on contrast and elevation
  const legibility = Math.min(100, Math.max(0, 
    40 + (contrast * 15) - (elevation * 0.5)
  ))

  const handlePreset = (dir: string) => {
    const map: Record<string, number> = { 'N': -90, 'E': 0, 'S': 90, 'W': 180 }
    setAzimuth(map[dir])
    setElevation(15)
  }

  return (
    <motion.div 
      className="h-screen flex flex-col noise-bg bg-ink-950 overflow-hidden"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
    >
      <header className="absolute top-0 left-0 right-0 p-6 flex justify-between items-center z-50 pointer-events-none">
        <Button variant="secondary" className="pointer-events-auto bg-ink-900/80 backdrop-blur-sm" onClick={() => navigate('/scan')}>
          <ArrowLeft className="mr-2" /> Back
        </Button>
        <div className="bg-ink-900/80 backdrop-blur-sm px-6 py-3 rounded-full border border-ink-800 pointer-events-auto flex items-center space-x-3">
          <span className="text-text-muted text-sm uppercase tracking-wider">Legibility</span>
          <div className="w-32 h-2 bg-ink-950 rounded-full overflow-hidden">
            <motion.div 
              className="h-full bg-saffron-500" 
              animate={{ width: `${legibility}%` }} 
              transition={{ type: "spring" }}
            />
          </div>
          <span className="font-mono text-saffron-500 font-bold">{legibility.toFixed(0)}</span>
        </div>
        <Button variant="primary" className="pointer-events-auto" onClick={() => navigate('/reader')}>
          Read Text <ArrowRight className="ml-2" />
        </Button>
      </header>

      {/* Main Viewer Area */}
      <div className="flex-1 relative cursor-move">
        {/* WebGL Relight Canvas */}
        <div className="absolute inset-0">
          <Canvas orthographic camera={{ zoom: 100, position: [0, 0, 10] }}>
            <MapControls enableRotate={false} />
            <React.Suspense fallback={null}>
              <LeafRelight lightAzimuth={azimuth} lightElevation={elevation} contrast={contrast} />
            </React.Suspense>
          </Canvas>
        </div>

        {/* Before/After Curtain (Phone Photo) */}
        <AnimatePresence>
          {showCurtain && (
            <motion.div 
              className="absolute inset-0 z-10 overflow-hidden"
              style={{ clipPath: `inset(0 ${100 - curtainPos}% 0 0)` }}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
            >
              <div className="absolute inset-0 bg-[url('/assets/leaf_phone.jpg')] bg-cover bg-center" />
              
              {/* Curtain Drag Handle */}
              <div 
                className="absolute top-0 bottom-0 w-1 bg-saffron-500 cursor-col-resize flex items-center justify-center"
                style={{ right: 0 }}
                onPointerMove={(e) => {
                  if (e.buttons === 1) {
                    const rect = e.currentTarget.parentElement?.getBoundingClientRect()
                    if (rect) {
                      const pct = ((e.clientX - rect.left) / rect.width) * 100
                      setCurtainPos(Math.min(100, Math.max(0, pct)))
                    }
                  }
                }}
              >
                <div className="w-8 h-12 bg-saffron-500 rounded-full flex items-center justify-center shadow-lg">
                  <ArrowLeft size={16} className="text-ink-950" />
                  <ArrowRight size={16} className="text-ink-950" />
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Bottom Controls */}
      <motion.div 
        className="absolute bottom-6 left-1/2 -translate-x-1/2 z-50 pointer-events-auto"
        initial={{ y: 50, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ delay: 0.5 }}
      >
        <Card className="flex items-center space-x-8 p-4 bg-ink-900/90 backdrop-blur-md">
          {/* Draggable Light Dial */}
          <div className="flex flex-col items-center">
            <span className="text-xs text-text-muted mb-2 uppercase tracking-widest">Light Dial</span>
            <div 
              className="relative w-16 h-16 rounded-full border-2 border-ink-800 bg-ink-950 overflow-hidden cursor-crosshair touch-none"
              onPointerMove={(e) => {
                if (e.buttons === 1) {
                  const rect = e.currentTarget.getBoundingClientRect()
                  const cx = rect.width / 2
                  const cy = rect.height / 2
                  const x = e.clientX - rect.left - cx
                  const y = e.clientY - rect.top - cy
                  
                  // Compute azimuth
                  let az = Math.atan2(y, x) * (180 / Math.PI)
                  // Compute elevation (distance from center, max 90 at center)
                  const dist = Math.min(1, Math.sqrt(x*x + y*y) / cx)
                  const el = Math.max(0, 90 * (1 - dist))
                  
                  setAzimuth(az)
                  setElevation(el)
                }
              }}
            >
              {/* Dial thumb indicator */}
              <motion.div 
                className="absolute w-4 h-4 bg-saffron-500 rounded-full shadow-[0_0_10px_#FFD98A]"
                style={{
                  top: '50%', left: '50%',
                  marginTop: -8, marginLeft: -8,
                  x: Math.cos(azimuth * Math.PI / 180) * (1 - elevation / 90) * 32,
                  y: Math.sin(azimuth * Math.PI / 180) * (1 - elevation / 90) * 32,
                }}
              />
            </div>
          </div>

          <div className="w-px h-12 bg-ink-800 mx-4" />

          {/* Light Presets */}
          <div className="flex flex-col items-center">
            <span className="text-xs text-text-muted mb-2 uppercase tracking-widest">Raking Light</span>
            <div className="flex space-x-2">
              {['N', 'E', 'S', 'W'].map(dir => (
                <button 
                  key={dir}
                  onClick={() => handlePreset(dir)}
                  className="w-10 h-10 rounded-full bg-ink-950 border border-ink-800 text-saffron-500 font-bold hover:bg-ink-800 transition-colors"
                >
                  {dir}
                </button>
              ))}
            </div>
          </div>

          <div className="w-px h-12 bg-ink-800" />

          {/* Contrast Slider */}
          <div className="flex flex-col items-center min-w-[150px]">
            <span className="text-xs text-text-muted mb-2 uppercase tracking-widest flex items-center"><SlidersHorizontal size={12} className="mr-1" /> Contrast</span>
            <input 
              type="range" 
              min="0.5" max="3" step="0.1" 
              value={contrast}
              onChange={e => setContrast(parseFloat(e.target.value))}
              className="w-full accent-saffron-500"
            />
          </div>

          <div className="w-px h-12 bg-ink-800" />

          {/* Toggles */}
          <div className="flex space-x-4">
            <Button variant={showCurtain ? 'primary' : 'secondary'} className="h-12 px-6 rounded-xl" onClick={() => setShowCurtain(!showCurtain)}>
              <Layers size={18} className="mr-2" />
              Compare Flat
            </Button>
          </div>
        </Card>
      </motion.div>
    </motion.div>
  )
}
